config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :public do
    resources :users, only: [:index, :show, :edit, :update]do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'public/relationships#followings', as: 'followings'
      get 'followers' => 'public/relationships#followers', as: 'followers'
    end

    resources :post_images, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :reposts, only: [:create, :destroy]
    end

    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]

    get '/search', to: 'searches#search'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>PetsStory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background" style="min-height:100vh; box-sizzing: border-box;">
      <div class="color">
        <header>
        <nav class="navbar navbar-expend-lg navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" href="/">
              <h1>Pets_Story</h1>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse show" id="navbarNavDropdown"style>
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to '投稿ファーム', new_public_post_image_path, class: "nav-link text-light mr-5" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '投稿一覧', public_post_images_path, class: "nav-link text-light mr-5" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'マイページ', public_user_path(current_user.id), class: "nav-link text-light mr-5" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'ユーザー一覧', public_users_path, class: "nav-link text-light mr-5" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-light mr-5" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-light mr-5" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path, class: "nav-link text-light mr-5" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer class="footer mt-auto py-3 bg-primary">
      <div class="container">
        <div class="row no-gutters">
          <div class="mx-auto">
            <p class="text-muted">©2023 Asami Inc</p>
          </div>
        </div>
      </div>
    </footer>
    </div>
  </div>
  </body>
</html>